# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: National Center for Charitable Statistics
short_title: NCCS
email: 
tagline: Short descriptor for site
description: >- # this means to ignore newlines until "baseurl:"
  Longer description for site
baseurl: "/nccs" # the subpath of your site if not served from the root, e.g. /nccs
url: "https://code.viget.com/" # the base hostname & protocol for your site, e.g. http://example.com
repository: "https://github.com/vigetlabs/nccs"
twitter_username: 
github_username:

# Navigation Items
# Entries here will show up in the _includes/nav.html partial
nav:
  - title: Data
    url: /datasets/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: Stories
    url: /stories/
  - title: About
    url: /about/
  - title: Really Long Nav Item
    url: /404/

# Build settings
sass:
  sass_dir: public/scss
plugins:
  - jekyll-feed

# Feed settings
feed:
  collections:
    - projects
    - datasets
    - stories

# Set defaults per collection type so they don't have to be specifed each time
defaults:
  -
    scope:
      path: "" # matches all paths
    values:
      layout: "default" # sets default
  -
    scope:
      path: ""
      type: "projects" # collection type
    values:
      layout: "project" # overrides previous default layout
      activeLink: "/projects/"
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
      activeLink: "/stories/"
  -
    scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
      grid: "sidebar"
      activeLink: "/datasets/"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      activeLink: "/publications/"

# Collections
collections:
  stories:
    output: true
    permalink: /:collection/:name/
  datasets:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "*.qmd"
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
