project:
  type: default
  render:
    - "_stories/"
    - "quarto"
  lib-dir: "public/vendor"
  output-dir: "_stories"
format:
  gfm:
    variant: gfm+yaml_metadata_block+definition_lists
    html-math-method: webtex
    preview-mode: raw
    fig-format: svg
    # mermaid-format: svg
    extract-media: '../../_stories'
